ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.14

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: 96d9af6217dc2855210655af7e1ff19d23d4e593  # frozen: v1
  hooks:
  - id: typos
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 0c8c15d8fe996493035be407c5cf4a288cf6bf8e  # frozen: v2.25.1
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: a55736a49694e73b4b885c78a827d9771515b9dd  # frozen: 1.7.1
  hooks:
  - id: tox-ini-fmt
- repo: https://github.com/rstcheck/rstcheck
  rev: 27258fde1ee7d3b1e6a7bbc58f4c7b1dd0e719e5  # frozen: v6.2.5
  hooks:
  - id: rstcheck
    additional_dependencies:
    - tomli==2.0.1
- repo: https://github.com/adamchainz/django-upgrade
  rev: bdcc9646c249f00ec9781751791e7b75b48b3722  # frozen: 1.31.1
  hooks:
  - id: django-upgrade
- repo: https://github.com/adamchainz/blacken-docs
  rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # frozen: 1.20.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==25.1.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
    additional_dependencies:
    - django-stubs==6.0.5
