ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.14

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: 12ffd4a04b4893ab75db66a59aaad2d996c3e982  # frozen: v1
  hooks:
  - id: typos
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: d600c142bb19f521ae6a6a345f94a2efd7937759  # frozen: v2.26.0
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 69e8f0ead1b1164c731b4a702896e3218feecf0b  # frozen: 1.8.1
  hooks:
  - id: tox-ini-fmt
- repo: https://github.com/rstcheck/rstcheck
  rev: 27a8027d6c6df787891a01b76e8298bac493fb58  # frozen: v6.3.0
  hooks:
  - id: rstcheck
    additional_dependencies:
    - tomli==2.0.1
- repo: https://github.com/adamchainz/django-upgrade
  rev: bdcc9646c249f00ec9781751791e7b75b48b3722  # frozen: 1.31.1
  hooks:
  - id: django-upgrade
- repo: https://github.com/adamchainz/blacken-docs
  rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # frozen: 1.20.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==25.1.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2  # frozen: v0.16.1
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 41e691678310dfd3833f7ab4e180ddb014310356  # frozen: v2.3.0
  hooks:
  - id: mypy
    additional_dependencies:
    - django-stubs==6.0.5
